# Default values for backup-test-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host:
  namespace: ~
  BoundServiceAccountName: ~
  secret:
    secretName: ~
    secretKey: ~
