{{- $databasePassword := "unbound" }}

{{- $databaseSecret := (lookup "v1" "Secret" .Values.host.namespace .Values.host.secret.dbSecretName ) }}
{{- if $databaseSecret }}
{{- $databasePassword = index $databaseSecret.data .Values.host.secret.dbSecretKey }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.host.secret.dbSecretName }}
  labels: {{ include "backup-test-init.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  password: {{ $databasePassword }}
type: Opaque
