kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-helm-deployer-binding
  labels: {{ include "backup-test-init.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.host.BoundServiceAccountName }}
    namespace: {{ .Values.host.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-helm-deployer-role
