{{- $gskey := "unbound" }}

{{- $gcsSecret := (lookup "v1" "Secret" .Values.host.namespace .Values.host.secret.secretName ) }}
{{- if $gcsSecret }}
{{- $gskey = index $gcsSecret.data "credentials.json" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.host.secret.secretName }}
  labels: {{ include "backup-test-init.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  credentials.json: {{ $gskey }}
type: Opaque
