app:
  showKCLogin: true
  sitewide_notice:
    content: <div class="alert alert-warning">This is the DEV environment.</div>

hostName: cas-cif-dev.apps.silver.devops.gov.bc.ca

db:
  preUpgradeCommand: |
    psql -v "ON_ERROR_STOP=1" <<EOF
      drop schema if exists sqitch cascade;
      drop schema if exists cif cascade;
      drop schema if exists cif_private cascade;
    EOF

deploy-db:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca

download-dags:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca
