defaultImageTag: latest # set to the GIT SHA1 in the Makefile
defaultImagePullPolicy: IfNotPresent
artifactoryServiceAccount: cas-artifact-download # The name of the ArtifactoryServiceAccount object created in the cas-provision chart

replicaCount: 2

image:
  app:
    repository: ghcr.io/bcgov/cas-cif-app
  schema:
    repository: ghcr.io/bcgov/cas-cif-schema
  psql:
    repository: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/cas-postgres
    tag: "0.3.0"
  casShelf:
    repository: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/cas-shelf-tfe-add-app
    tag: "0.1"
  backupTest:
    repository: ghcr.io/bcgov/cas-cif-test-backups

app:
  sitewide_notice:
    content: ""
  port: 3000
  probesPort: 9000
  showKCLogin: false

db:
  name: cif
  appUser: cifapp
  ownerUser: cif
  # A shell script that will be executed in a pre-upgrade job, on the psql image.
  preUpgradeCommand: ~
  restore:
    enabled: false
    targetTimestamp: ~ # The target timestamp to restore the database to. Format: "2021-06-09 09:00:00-07"

hostName: ~

certbot:
  image:
    pullPolicy: IfNotPresent
  certbot:
    email: ggircs@gov.bc.ca

resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

deploy-db:
  enabled: true
  airflowEndpoint: ~
  dagId: cas_cif_deploy_db
  helm:
    hook: false

download-dags:
  enabled: true
  airflowEndpoint: ~
  dagId: fetch_and_save_dag_from_github
  helm:
    hook: "pre-install,pre-upgrade"

ggircs:
  service: cas-ggircs-patroni
  instanceName: cas-ggircs

metabase:
  instanceName: cas-metabase

devops:
  image:
    repository: hashicorp/terraform
    pullPolicy: Always
    tag: "1.4.6"

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 64Mi

terraform-bucket-provision:
  terraform:
    namespace_apps: '["cif-backups", "cif-documents"]'
