app:
  sitewide_notice:
    content: <div class="alert alert-warning">This is the TEST environment.</div>

hostName: test.cif.gov.bc.ca

db:
  postUpgrade: true
  upgradeCommand: |
    psql -v "ON_ERROR_STOP=1" <<EOF
      drop schema if exists sqitch cascade;
      drop schema if exists cif cascade;
      drop schema if exists cif_private cascade;
    EOF

deploy-db:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

download-dags:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca
