apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "terraform-secret-admin"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
