apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "terraform-kubernetes-service-account-secret-admin-binding"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "terraform-secret-admin"
subjects:
  - kind: ServiceAccount
    name: "terraform-kubernetes-service-account"
    namespace: {{ .Release.Namespace }}
