{{- $currentNamespace := .Release.Namespace }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-database-backups
  labels:
{{ include "cas-cif.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 800
      template:
        metadata:
          labels: {{ include "cas-cif.labels" . | nindent 14 }}
        spec:
          activeDeadlineSeconds: 800
          restartPolicy: Never
          serviceAccountName: deployer
          containers:
          - name: deploy-test-cluster
            image: {{ .Values.image.backupTest.repository }}:{{ default .Values.defaultImageTag .Values.image.backupTest.tag }}
            imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.backupTest.pullPolicy }}
            resources:
              limits:
                cpu: 800m
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 256Mi
            command:
            - /bin/sh
            - -c
            - |
                set -euo pipefail;
                helm install --timeout 20m -n {{ include "cas-cif.namespacePrefix" . }}-tools backup-test ./backup-test --set host.namespace={{ $currentNamespace }};
