apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-database-backups
  labels:
{{ include "backup-test.labels" . | indent 4 }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployer
          containers:
          - name: deploy-test-cluster
            image: <ourimage>
            command:
            - /bin/sh
            - -c
            - |
                set -euo pipefail;
                helm install -n {{ cas-cif.namespacePrefix }}-tools backup-test \
                --set host.namespace={{ Release.Namespace }} \
                --set host.secret.secretName=gcp-{{ .Release.Namespace }}-cif-backups-service-account-key \
                --set host.secret.secretKey=credentials.json \
                && ./check_for_recent_timestamps \
                && helm uninstall -n {{cas-cif.namespacePrefix}}-tools backup-test
          restartPolicy: Never
