apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-database-backups
  labels:
{{ include "cas-cif.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels: {{ include "cas-cif.labels" . | nindent 14 }}
        spec:
          activeDeadlineSeconds: 600
          restartPolicy: Never
          serviceAccountName: deployer
          initContainers:
          - name: test-for-timestamp
            image: postgres:14.6-alpine
            imagePullPolicy: {{ default .Values.defaultImagePullPolicy "Always" }}
            env:
              - name: CIF_BACKUP_HOST
                valueFrom:
                  secretKeyRef:
                    key: host
                    name: {{ .Release.Name }}-defined-backup-password
              - name: CIF_BACKUP_PASS
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: {{ .Release.Name }}-defined-backup-password
            command:
            - /bin/bash
            - -c
            - |
                set -euo pipefail;
                declare -i VALUE;
                export PGPASSWORD="$(CIF_BACKUP_PASS)";
                VALUE=$(psql -U postgres -h ${CIF_BACKUP_HOST} -qtAX -d cif -c "select count(*) from cif_private.full_backup_log where full_backup_timestamp > now() - interval '12 hours'");
                if [[ $VALUE -lt 1 ]] ; then
                  echo 'no timestamp found'
                  exit 1
                else
                  echo 'timestamp found, backup ok...uninstalling test cluster';
                  exit 0;
                fi;
          containers:
          - name: uninstall-backup-chart
            image: {{ .Values.image.backupTest.repository }}:{{ default .Values.defaultImageTag .Values.image.backupTest.tag }}
            imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.backupTest.pullPolicy }}
            resources:
              limits:
                cpu: 800m
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 256Mi
            command:
            - /bin/sh
            - -c
            - |
                set -euo pipefail;
                echo 'timestamp found, backup ok...uninstalling test cluster';
                helm uninstall -n {{ include "cas-cif.namespacePrefix" . }}-tools backup-test;
