{{- $currentNamespace := .Release.Namespace }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-database-backups
  labels:
{{ include "cas-cif.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels: {{ include "cas-cif.labels" . | nindent 14 }}
        spec:
          activeDeadlineSeconds: 600
          restartPolicy: Never
          serviceAccountName: deployer
          containers:
          - name: deploy-test-cluster
            image: {{ .Values.image.backupTest.repository }}:{{ default .Values.defaultImageTag .Values.image.backupTest.tag }}
            imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.backupTest.pullPolicy }}
            resources:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 64Mi
            command:
            - /bin/sh
            - -c
            - |
                set -euo pipefail;
                helm install -n {{ include "cas-cif.namespacePrefix" . }}-tools backup-test \
                --set host.namespace={{ $currentNamespace }} \
                --set host.secret.secretName=gcp-{{ $currentNamespace }}-cif-backups-service-account-key \
                --set host.secret.secretKey=credentials.json;
