{{- $databasePassword := (randAlphaNum 32) | b64enc | quote }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cas-cif.fullname" . }}-defined-backup-password
  labels: {{ include "cas-cif.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  password: {{ $databasePassword }}
type: Opaque
