{{- $databasePassword := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (print (include "cas-cif.fullname" .)) "-defined-backup-password" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $databasePassword = index $secret.data "password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "cas-cif.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  password: {{ $databasePassword }}
type: Opaque
