apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: c53ff1-dev
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                5
        Daemon               Off
        Parsers_File         /var/log/parsers.conf
        Log_Level            info
        HTTP_Server          On
        HTTP_Listen          0.0.0.0
        HTTP_Port            2020
        Storage_Type         filesystem

    [INPUT]
        Name                tail
        Path                /var/log/oc-cif-test.log
        Tag                 oc-cif-test
        Mem_Buf_Limit        5MB
        DB                  /var/log/flb_kube.db
        Refresh_Interval     10
        Rotate_Wait          5
        Ignore_Older         24h

    [OUTPUT]
        Name                es
        Match               *
        Host                elasticsearch.9212c9-tools.svc.cluster.local
        Port                9200
        Index               ciif-logs
        Logstash_Prefix     ciif-logs
        Logstash_DateFormat %Y.%m.%d
        Logstash_Format     On
        Retry_Limit         False
        Suppress_Type_Name  On
        Type                _doc
        Time_Key            @timestamp
        Time_Key_Format     iso8601

  parsers.conf: |
    [PARSER]
        Name                json
        Format              json
        Time_Key            timestamp
        Decode_Field_as     escaped_utf8 log do_next
        Decode_Field_as     json log
