apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-logger-rolebinding
subjects:
  - kind: ServiceAccount
    name: pod-logger
    namespace: c53ff1-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-logger-role
