apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-logger-role
  namespace: c53ff1-dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list","watch"]
