apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ template "cas-cif.fullname" . }}-postgres
  labels: {{ include "cas-cif.labels" . | nindent 4 }}
  {{- if .Values.db.restore.enabled }}
  annotations:
    postgres-operator.crunchydata.com/pgbackrest-restore: {{ now | date "2006-01-02 15:04:05.000000" | quote }}
  {{- end }}
spec:
  image: ""
  metadata:
    labels: {{ include "cas-cif.labels" . | nindent 6 }}
  postgresVersion: 14
  instances:
    - name: pgha1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
            cpu: 15m
            memory: 600Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        storageClassName: netapp-block-standard
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: {{ template "cas-cif.fullname" . }}-postgres
                  postgres-operator.crunchydata.com/instance-set: pgha1
  proxy:
    pgBouncer:
      image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbouncer:ubi8-1.18-0
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      config:
        global:
          client_tls_sslmode: disable
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: {{ template "cas-cif.fullname" . }}-postgres
                  postgres-operator.crunchydata.com/role: pgbouncer
  users:
    - name: cif
      databases:
        - cif
      options: "CREATEROLE"
    - name: cifapp
      databases:
        - cif
    - name: postgres
      databases:
        - cif
  backups:
    pgbackrest:
      image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest:ubi8-2.41-4
    {{- if .Values.db.restore.enabled }}
      restore:
        enabled: true
        repoName: repo1
        options:
        - --type=time
        - --target={{ .Values.db.restore.targetTimestamp | quote }}
    {{- end }}
      global:
        repo1-retention-full: "90"
        repo1-retention-full-type: time
      configuration:
        - configMap:
            name: {{ template "cas-cif.fullname" . }}-pgbackrest
        - secret:
            name: gcp-{{ .Release.Namespace }}-cif-backups-service-account-key
            items:
              - key: credentials.json
                path: gcs-key.json
      repos:
        - name: repo1
          gcs:
            bucket: {{ .Release.Namespace }}-cif-backups
          schedules:
            full: "0 8 * * *"
            # run incremental backup every 4 hours, except at 8am UTC (when the full backup is running)
            incremental: "0 0,4,12,16,20 * * *"
  monitoring:
    pgmonitor:
      exporter:
        image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres-exporter:ubi8-5.3.1-0
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
