{{- if not (hasSuffix "-prod" .Release.Namespace)}}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "cas-cif.fullname" . }}
  labels: {{ include "cas-cif.labels" . | nindent 4 }}

spec:
  host: {{ .Values.hostName }}
  port:
    targetPort: {{ template "cas-cif.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ template "cas-cif.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- end -}}
