{{- $hostSecret := (lookup "v1" "Secret" .Values.host.namespace .Values.host.secret.secretName ) }}
{{- $credentialSecret := "null" }}
{{- if $hostSecret }}
{{- $credentialSecret = index $hostSecret.data .Values.host.secret.secretKey}}
{{- else }}
{{- print "WARNING credentialSecret does not exist, connection to backups fail" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: gcs-credentials
  labels: {{ include "backup-test.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  credentials: {{ $credentialSecret }}
