apiVersion: v1
kind: Secret
metadata:
  name: gcs-credentials
  labels: {{ include "backup-test.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  credentials: {{ .Values.host.secret.credentials | quote }}
