# Default values for backup-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

host:
  namespace: cif-namespace
  secret:
    secretName: cif-sa-secret
    secretKey: cif-gcp-credentials

db:
  restore:
    enabled: true
    targetTimestamp: now - interval
