name: Pre-release checks

on:
  push:
    branches: [main]

jobs:
  sqitch-plan-ends-with-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.bin/sqitch-last-change-is-tag.sh schema
